// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9L4Lt11E1yCpShLp9Sl8yAqRQ6298Y1U',
    appId: '1:282607814954:web:bbd26aa0dd4d958e25b653',
    messagingSenderId: '282607814954',
    projectId: 'touchhealth-app',
    authDomain: 'touchhealth-app.firebaseapp.com',
    storageBucket: 'touchhealth-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9L4Lt11E1yCpShLp9Sl8yAqRQ6298Y1U',
    appId: '1:282607814954:android:bbd26aa0dd4d958e25b653',
    messagingSenderId: '282607814954',
    projectId: 'touchhealth-app',
    storageBucket: 'touchhealth-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9L4Lt11E1yCpShLp9Sl8yAqRQ6298Y1U',
    appId: '1:282607814954:ios:bbd26aa0dd4d958e25b653',
    messagingSenderId: '282607814954',
    projectId: 'touchhealth-app',
    storageBucket: 'touchhealth-app.firebasestorage.app',
    iosBundleId: 'com.example.touch_health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9L4Lt11E1yCpShLp9Sl8yAqRQ6298Y1U',
    appId: '1:282607814954:ios:bbd26aa0dd4d958e25b653',
    messagingSenderId: '282607814954',
    projectId: 'touchhealth-app',
    storageBucket: 'touchhealth-app.firebasestorage.app',
    iosBundleId: 'com.example.touch_health.RunnerTests',
  );
}
